name: "basic.yml"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: "boolean"
        description: "Run the build with tmate debugging enabled"
  merge_group:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}:${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: "build"
    runs-on:
      - "lab"
    timeout-minutes: 300
    permissions:
      issues: "none"
      pull-requests: "none"
      packages: "write"
      contents: "read"
      id-token: "write"
    steps:
      - name: "log KUBE_NODE"
        run: |
          echo "$KUBE_NODE"

      - uses: "actions/checkout@v5"
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "install nix"
        uses: "cachix/install-nix-action@v31"

      - run: |
          sudo chown -R "$(id -u):$(id -g)" /nix

      - name: "login to ghcr.io"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - uses: "dtolnay/rust-toolchain@stable"

      - name: "scratch test"
        run: |
          docker pull ghcr.io/githedgehog/testn/n-vm:0.0.2
          docker run --privileged --rm --cap-add=SYS_ADMIN busybox:latest sh -c "echo 4 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages && cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages"
          cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
          echo 4 | sudo tee /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
          cargo test --package=scratch

      - name: "build"
        run: |
          nix build -f default.nix n-vm.container
          docker load < ./result
          docker build --tag ghcr.io/githedgehog/testn/n-vm:0.0.0 .
          # TODO: push to ghcr.io (this requires plumbing the version from git into the build)

      - name: "Setup tmate session for debug"
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: "mxschmitt/action-tmate@v3"
        timeout-minutes: 60
        with:
          limit-access-to-actor: true
